version: '3.8'

services:
  # Laravel Backend
  app:
    build:
      context: ./laravelBackend
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravelBackend:/var/www
    networks:
      - app-network
    depends_on:
      - db
  web:
    image: nginx:alpine
    container_name: laravel-webserver
    volumes:
      - ./laravelBackend:/var/www
      - ./laravelBackend/docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - app-network

  # Vue.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "3000:3000"  # Expose for Vue.js app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
